// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeterinaryClinic.API.Data;

#nullable disable

namespace VeterinaryClinic.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605170605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.AdoptionAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vaccines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdoptionAnimals");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.AdoptionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionAnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdoptionAnimalId");

                    b.HasIndex("ClientId");

                    b.ToTable("AdoptionRequests");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PetId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Inflamație a urechii externe",
                            Name = "Otită externă",
                            Observations = "Monitorizare săptămânală. Evitați intrarea apei în urechi.",
                            Species = "Câine",
                            Treatment = "Curățare auriculară cu soluție antiseptică. Picături auriculare cu antibiotic și antiinflamator (ex: Otomax) timp de 7-10 zile."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Reacție alergică cutanată",
                            Name = "Dermatită alergică",
                            Observations = "Identificați și eliminați alergenul. Dietă hipoalergenică recomandată.",
                            Species = "",
                            Treatment = "Antihistaminice (Cetirizină 5mg/zi). Șampoane hipoalergenice. Corticosteroizi în cazuri severe (Prednisolon 0.5mg/kg/zi, 5 zile)."
                        },
                        new
                        {
                            Id = 3,
                            Description = "Inflamație a tractului gastrointestinal",
                            Name = "Gastroenterită",
                            Observations = "Monitorizați hidratarea. Dacă vărsăturile persistă peste 24h, repetați consultul.",
                            Species = "",
                            Treatment = "Dietă blândă 48-72h (orez fiert + pui fiert fără sare). Hidratare corespunzătoare. Probiotice (Fortiflora 1 plic/zi, 7 zile). Metronidazol 15mg/kg de 2 ori pe zi, 5 zile dacă este necesar."
                        },
                        new
                        {
                            Id = 4,
                            Description = "Infecție bacteriană a tractului urinar",
                            Name = "Infecție urinară",
                            Observations = "Recoltați urocultură dacă infecțiile sunt recurente. Reevaluare la 2 săptămâni.",
                            Species = "",
                            Treatment = "Amoxicilină-clavulanat 15mg/kg de 2 ori pe zi, 10-14 zile. Creșteți aportul de apă. Urocolvin sau alt supliment urinar."
                        },
                        new
                        {
                            Id = 5,
                            Description = "Inflamație a conjunctivei oculare",
                            Name = "Conjunctivită",
                            Observations = "Evitați expunerea la vânt și praf. Dacă nu se ameliorează în 5 zile, consultați un oftalmolog veterinar.",
                            Species = "",
                            Treatment = "Curățarea ochilor cu ser fiziologic steril. Picături oftalmice cu antibiotic (Tobramicină sau Cloramfenicol) de 3 ori pe zi, 7 zile."
                        },
                        new
                        {
                            Id = 6,
                            Description = "Infestare cu paraziți intestinali",
                            Name = "Parazitoză intestinală",
                            Observations = "Igienizarea mediului. Deparazitare și la alți animale de companie din gospodărie.",
                            Species = "",
                            Treatment = "Fenbendazol 50mg/kg/zi, 3-5 zile sau Pyrantel 5mg/kg doză unică. Deparazitare internă periodică la 3-6 luni."
                        },
                        new
                        {
                            Id = 7,
                            Description = "Insuficiență a reglării glicemice",
                            Name = "Diabet zaharat",
                            Observations = "Educarea proprietarului privind semnele de hipoglicemie. Control lunar.",
                            Species = "",
                            Treatment = "Insulină (dozaj individualizat în funcție de glicemie). Dietă cu conținut redus de carbohidrați. Monitorizare glicemie zilnică."
                        },
                        new
                        {
                            Id = 8,
                            Description = "Producție insuficientă de hormoni tiroidieni",
                            Name = "Hipotiroidism",
                            Observations = "Tratament pe viață. Control tiroidian la 6 luni.",
                            Species = "Câine",
                            Treatment = "Levotiroxină sodică 0.02mg/kg de 2 ori pe zi. Ajustarea dozei după 4-6 săptămâni în funcție de TSH."
                        },
                        new
                        {
                            Id = 9,
                            Description = "Inflamație a mucoasei bucale",
                            Name = "Stomatită",
                            Observations = "Periaj dentar regulat. Dietă cu hrană umedă în perioada de recuperare.",
                            Species = "",
                            Treatment = "Curățare dentară profesională sub anestezie. Antibiotice (Clindamicină 5mg/kg de 2 ori pe zi, 10 zile). Gel oral antiseptic local."
                        },
                        new
                        {
                            Id = 10,
                            Description = "Inflamație articulară degenerativă",
                            Name = "Artrită",
                            Observations = "Evitați efortul fizic intens. Suprafețe moi pentru odihnă. Monitorizare renală la tratament lung cu AINS.",
                            Species = "",
                            Treatment = "Meloxicam 0.1mg/kg/zi cu mâncare. Suplimente condroprotectoare (Glucozamină + Condroitin). Fizioterapie recomandată."
                        });
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<int>("TestType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetId")
                        .HasColumnType("integer");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PetId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Vaccines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.AdoptionRequest", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.AdoptionAnimal", "AdoptionAnimal")
                        .WithMany("AdoptionRequests")
                        .HasForeignKey("AdoptionAnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinaryClinic.API.Models.Entities.Client", "Client")
                        .WithMany("AdoptionRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdoptionAnimal");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Appointment", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinaryClinic.API.Models.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinaryClinic.API.Models.Entities.Pet", "Pet")
                        .WithMany("Appointments")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Doctor");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Client", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Doctor", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.LabResult", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.Pet", "Pet")
                        .WithMany("LabResults")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.MedicalRecord", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.Diagnosis", "DiagnosisRef")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VeterinaryClinic.API.Models.Entities.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinaryClinic.API.Models.Entities.Pet", "Pet")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiagnosisRef");

                    b.Navigation("Doctor");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Pet", b =>
                {
                    b.HasOne("VeterinaryClinic.API.Models.Entities.Client", "Client")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.AdoptionAnimal", b =>
                {
                    b.Navigation("AdoptionRequests");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Client", b =>
                {
                    b.Navigation("AdoptionRequests");

                    b.Navigation("Appointments");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Diagnosis", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("VeterinaryClinic.API.Models.Entities.Pet", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("LabResults");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
